ersion: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: gratitudeya/certificates_frontend:latest
    container_name: frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
     - db

  backend:
    image: gratitudeya/certificates_backend:latest
    pull_policy: always
    container_name: backend
    volumes:
     - static_value:/app/static/
     - media_value:/app/media/
    depends_on:
     - db
    env_file:
     - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    env_file:
      - ./.env
    depends_on:
      - backend
      - frontend

volumes:
  data_value:
  static_value:
  media_value: