# Generated by Django 3.2 on 2023-08-17 21:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Название документа')),
                ('category', models.CharField(choices=[('diplomas', 'Дипломы'), ('certificates', 'Сертификаты'), ('appreciations', 'Благодарности'), ('awards', 'Грамоты'), ('others', 'Другое')], max_length=15, verbose_name='Категория')),
                ('preview', models.CharField(max_length=255, verbose_name='Превью')),
                ('background_image', models.CharField(max_length=255, verbose_name='Фон')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Размер элемента')),
                ('stamp_image', models.CharField(max_length=255, verbose_name='Изображение элемента')),
                ('coordinate_y', models.IntegerField(verbose_name='Координата Y')),
                ('coordinate_x', models.IntegerField(verbose_name='Координата X')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
            options={
                'verbose_name': 'Штамп',
                'verbose_name_plural': 'Штампы',
                'ordering': ('document_id',),
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('coordinate_y', models.IntegerField(verbose_name='Координата Y')),
                ('coordinate_x', models.IntegerField(verbose_name='Координата X')),
                ('font', models.CharField(max_length=100, verbose_name='Название шрифта')),
                ('font_size', models.IntegerField(verbose_name='Размер шрифта')),
                ('font_color', models.CharField(max_length=100, verbose_name='Цвет шрифта')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
    ]
