# Generated by Django 3.2 on 2023-08-22 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('diplomas', 'Дипломы'), ('certificates', 'Сертификаты'), ('appreciations', 'Благодарности'), ('awards', 'Грамоты'), ('others', 'Другое')], db_index=True, help_text='Введите категорию документа', max_length=55, verbose_name='Категория')),
                ('slug', models.SlugField(blank=True, help_text='Введите уникальный префикс', max_length=55, unique=True, verbose_name='Уникальный префикс')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.AlterField(
            model_name='document',
            name='background_image',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(db_index=True, help_text='Введите название документа', max_length=255, validators=[django.core.validators.MinLengthValidator(6, message='Введите слово больше 6 символов')], verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='field',
            name='font',
            field=models.CharField(help_text='Введите название шрифта', max_length=50, verbose_name='Название шрифта'),
        ),
        migrations.AlterField(
            model_name='field',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=14, help_text='Введите размер шрифта', validators=[django.core.validators.MinValueValidator(8, message='Введите число начиная от 8')], verbose_name='Размер шрифта'),
        ),
        migrations.AlterField(
            model_name='field',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст поля'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='size',
            field=models.PositiveSmallIntegerField(verbose_name='Размер элемента'),
        ),
        migrations.AddField(
            model_name='document',
            name='category_id',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.category'),
        ),
    ]
