# Generated by Django 3.2 on 2023-08-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='certificate',
            new_name='document',
        ),
    ]
