# Generated by Django 3.2 on 2023-08-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_rename_certificate_favourite_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='textFields',
            field=models.ManyToManyField(to='documents.TextField', verbose_name='Текстовое поле'),
        ),
    ]
