# Generated by Django 3.2 on 2023-08-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='textFields',
            new_name='text_fields',
        ),
    ]
