# Generated by Django 3.2 on 2023-08-31 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_rename_textfields_document_text_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_y', models.IntegerField(verbose_name='Координата Y')),
                ('coordinate_x', models.IntegerField(verbose_name='Координата X')),
                ('image', models.ImageField(blank=True, upload_to='elements/')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.AlterModelOptions(
            name='templatecolor',
            options={'verbose_name': 'Цвет фона', 'verbose_name_plural': 'Цвета фона'},
        ),
        migrations.AlterModelOptions(
            name='textfield',
            options={'verbose_name': 'Поле', 'verbose_name_plural': 'Поля'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='images',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text_fields',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='fonts',
        ),
        migrations.AddField(
            model_name='document',
            name='background',
            field=models.ImageField(blank=True, upload_to='backgrounds/', verbose_name='BackgroundImage'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfield',
            name='font',
            field=models.CharField(default=1, help_text='Введите название шрифта', max_length=50, verbose_name='Название шрифта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfield',
            name='is_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textfield',
            name='is_italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(db_index=True, help_text='Введите название документа', max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='text_decoration',
            field=models.CharField(choices=[('underline', 'подчеркнутый'), ('strikethrough', 'зачеркнутый'), (False, 'обычный')], default=False, max_length=20, verbose_name='Подчёркивание шрифта'),
        ),
        migrations.DeleteModel(
            name='Font',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='element',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
    ]
