# Generated by Django 3.2 on 2023-09-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20230831_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_horizontal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textfield',
            name='align',
            field=models.CharField(choices=[('left', ''), ('right', ''), ('center', '')], default='left', max_length=6),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='text_decoration',
            field=models.CharField(choices=[('underline', 'подчеркнутый'), ('strikethrough', 'зачеркнутый'), ('none', 'обычный')], default='none', max_length=20, verbose_name='Подчёркивание шрифта'),
        ),
    ]
