# Generated by Django 4.2.4 on 2023-09-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_favourite_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('diplomas', 'Дипломы'), ('certificates', 'Сертификаты'), ('appreciations', 'Благодарности'), ('awards', 'Грамоты')], db_index=True, help_text='Введите категорию документа', max_length=55, verbose_name='Категория'),
        ),
    ]
