# Generated by Django 4.2.4 on 2023-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(max_length=100)),
                ('is_bold', models.BooleanField()),
                ('is_italic', models.BooleanField()),
                ('font_file', models.FileField(upload_to='fonts/')),
            ],
        ),
        migrations.AlterField(
            model_name='textfield',
            name='align',
            field=models.CharField(choices=[('left', 'по левому краю'), ('right', 'по правому краю'), ('center', 'по центру')], default='left', max_length=6),
        ),
    ]
