# Generated by Django 4.2.4 on 2023-09-21 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_alter_category_name_alter_favourite_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='font',
            options={'verbose_name': 'Шрифт', 'verbose_name_plural': 'Шрифты'},
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='is_bold',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='is_italic',
        ),
        migrations.AlterField(
            model_name='textfield',
            name='font',
            field=models.ForeignKey(help_text='Введите название шрифта', max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='documents.font', verbose_name='Название шрифта'),
        ),
    ]
