# Generated by Django 3.2 on 2023-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_image_user_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_image',
            field=models.ImageField(blank=True, default='avatar_image.jpg', upload_to='users/', verbose_name='Аватарка'),
        ),
    ]
