# Generated by Django 4.2.4 on 2023-08-31 16:00

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.IntegerField(default=users.models.activation_code, max_length=6, verbose_name='Код'),
        ),
    ]
