# Generated by Django 4.2.4 on 2023-08-31 16:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.PositiveIntegerField(default=users.models.activation_code, verbose_name='Код'),
        ),
    ]
